-- A DuelElo_Ladder data file as generated by the site (SPEC §2.7), region US.
DuelEloLadderData = DuelEloLadderData or {}
DuelEloLadderData[1] = {
    season = 1, generated = 1791500000,
    confirmed = "100000:200000 123:456 bad#id 789:12",
    players = {
        ["Ashvale-Sargeras"] = "1834|2|ELITE|S1E,FD,T10|0",
        ["Thrall-Area52"] = "1902|1|ELITE|C1,FD|0",
        ["Jaina-Area52"] = "1610|3|DUELIST||0",
        ["Cheater-Illidan"] = "1700||DUELIST||1",
        ["Newbie-Sargeras"] = "1250||CHALLENGER||0",
        ["Broken-Realm"] = "not an entry",
    },
}
